#!/bin/bash
STACK_NAME="my-simple-stack"
REGION="us-east-1"

aws cloudformation deploy \
  --stack-name $STACK_NAME \
  --template-file template.yml \
  --region $REGION \
  --capabilities CAPABILITY_IAM